#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
	deb-systemd-helper mask 'accel-web-manager.service' >/dev/null || true
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
	deb-systemd-helper purge 'accel-web-manager.service' >/dev/null || true
	deb-systemd-helper unmask 'accel-web-manager.service' >/dev/null || true
    fi
fi

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi

exit 0
